config/routes.rb
Practicantes::Application.routes.draw do
  devise_for :students
  devise_for :enterprises

  resources :offers
  resources :cities
  resources :enterprises
  resources :careers
  resources :areas
  resource :search, only: [:show, :create]
  resources :skills, only: [:index]

  root :to => 'pages#index'

end

app/models/career.rb
# == Schema Information
#
# Table name: careers
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  area_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Career < ActiveRecord::Base
  attr_accessible :area_id, :name
  
  #relations
  has_many :profiles
  belongs_to :area
end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
  # GET /careers
  # GET /careers.json
  def index
    @careers = Career.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @careers }
    end
  end

  # GET /careers/1
  # GET /careers/1.json
  def show
    @career = Career.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @career }
    end
  end

  # GET /careers/new
  # GET /careers/new.json
  def new
    @career = Career.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @career }
    end
  end

  # GET /careers/1/edit
  def edit
    @career = Career.find(params[:id])
  end

  # POST /careers
  # POST /careers.json
  def create
    @career = Career.new(params[:career])

    respond_to do |format|
      if @career.save
        format.html { redirect_to @career, notice: 'Career was successfully created.' }
        format.json { render json: @career, status: :created, location: @career }
      else
        format.html { render action: "new" }
        format.json { render json: @career.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /careers/1
  # PUT /careers/1.json
  def update
    @career = Career.find(params[:id])

    respond_to do |format|
      if @career.update_attributes(params[:career])
        format.html { redirect_to @career, notice: 'Career was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @career.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /careers/1
  # DELETE /careers/1.json
  def destroy
    @career = Career.find(params[:id])
    @career.destroy

    respond_to do |format|
      format.html { redirect_to careers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/views/careers/_form.html.haml
= form_for @career do |f|
  -if @career.errors.any?
    #error_explanation
      %h2= "#{pluralize(@career.errors.count, "error")} prohibited this career from being saved:"
      %ul
        - @career.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :area_id
    = f.number_field :area_id
  .actions
    = f.submit 'Save'

app/views/careers/edit.html.haml
%h1 Editing career

= render 'form'

= link_to 'Show', @career
\|
= link_to 'Back', careers_path

app/views/careers/index.html.haml
%h1 Listing careers

%table
  %tr
    %th Name
    %th Area
    %th
    %th
    %th

  - @careers.each do |career|
    %tr
      %td= career.name
      %td= career.area_id
      %td= link_to 'Show', career
      %td= link_to 'Edit', edit_career_path(career)
      %td= link_to 'Destroy', career, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Career', new_career_path

app/views/careers/new.html.haml
%h1 New career

= render 'form'

= link_to 'Back', careers_path

app/views/careers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @career.name
%p
  %b Area:
  = @career.area_id

= link_to 'Edit', edit_career_path(@career)
\|
= link_to 'Back', careers_path