config/routes.rb
Practicantes::Application.routes.draw do
  devise_for :students
  devise_for :enterprises

  resources :offers
  resources :cities
  resources :enterprises
  resources :careers
  resources :areas
  resource :search, only: [:show, :create]
  resources :skills, only: [:index]

  root :to => 'pages#index'

end

app/models/area.rb
# == Schema Information
#
# Table name: areas
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Area < ActiveRecord::Base
  attr_accessible :name
  
  #relations
  has_many :careers
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @areas }
    end
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
    @area = Area.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @area }
    end
  end

  # GET /areas/new
  # GET /areas/new.json
  def new
    @area = Area.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @area }
    end
  end

  # GET /areas/1/edit
  def edit
    @area = Area.find(params[:id])
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(params[:area])

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render json: @area, status: :created, location: @area }
      else
        format.html { render action: "new" }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /areas/1
  # PUT /areas/1.json
  def update
    @area = Area.find(params[:id])

    respond_to do |format|
      if @area.update_attributes(params[:area])
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area = Area.find(params[:id])
    @area.destroy

    respond_to do |format|
      format.html { redirect_to areas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.haml
= form_for @area do |f|
  -if @area.errors.any?
    #error_explanation
      %h2= "#{pluralize(@area.errors.count, "error")} prohibited this area from being saved:"
      %ul
        - @area.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/areas/edit.html.haml
%h1 Editing area

= render 'form'

= link_to 'Show', @area
\|
= link_to 'Back', areas_path

app/views/areas/index.html.haml
%h1 Listing areas

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @areas.each do |area|
    %tr
      %td= area.name
      %td= link_to 'Show', area
      %td= link_to 'Edit', edit_area_path(area)
      %td= link_to 'Destroy', area, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Area', new_area_path

app/views/areas/new.html.haml
%h1 New area

= render 'form'

= link_to 'Back', areas_path

app/views/areas/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @area.name

= link_to 'Edit', edit_area_path(@area)
\|
= link_to 'Back', areas_path