config/routes.rb
Practicantes::Application.routes.draw do
  devise_for :students
  devise_for :enterprises

  resources :offers
  resources :cities
  resources :enterprises
  resources :careers
  resources :areas
  resource :search, only: [:show, :create]
  resources :skills, only: [:index]

  root :to => 'pages#index'

end

app/models/offer.rb
# == Schema Information
#
# Table name: offers
#
#  id            :integer          not null, primary key
#  enterprise_id :integer
#  name          :string(255)
#  description   :string(255)
#  city_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  skills        :string(255)
#  wanted_skills :string(255)
#

class Offer < ActiveRecord::Base
  attr_accessible :city_id, :description, :enterprise_id, :name,
    :skills, :wanted_skills, :offers_attributes, :skill_list, :wanted_skill_list

  #relations
  belongs_to :enterprise
  belongs_to :city

  has_many  :offer_profiles
  has_many :profiles, through: :offer_profiles

  acts_as_taggable
  acts_as_taggable_on :skills, :wanted_skills

  accepts_nested_attributes_for :profiles, :reject_if => :reject_profile,
    :allow_destroy => true

  def self.search(params = nil)
    # search(params)
    unless params.blank?
      scope = all
      scope += tagged_with(params[:skills], on: :skills) if params[:skills].present?
      scope += tagged_with(params[:wanted_skills], on: :wanted_skills) if params[:wanted_skills].present?
    end
    scope
  end

  def self.search_skills(skill)
    ActsAsTaggableOn::Tag.search(name_contains: skill).all
  end

  def reject_profile(attributes)
    attributes['profile'].blank?
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offers }
    end
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
    @offer = Offer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @offer }
    end
  end

  # GET /offers/new
  # GET /offers/new.json
  def new
    @offer = Offer.new
    @cities = City.find(:all, :order => 'name').map{|x| [x.name, x.id]}

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @offer }
    end
  end

  # GET /offers/1/edit
  def edit
    @offer = Offer.find(params[:id])
  end

  # POST /offers
  # POST /offers.json
  def create
    params[:offer][:enterprise_id] = current_enterprise
    @offer = Offer.new(params[:offer])

    respond_to do |format|
      if @offer.save
        @offer.skill_list = params[:skills]
        @offer.wanted_skill_list = params[:wanted_skills]
        
        params[:profile_ids].each do |profile|
        OfferProfile.create(offer_id: @offer, profile_id: profile)
        end
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render json: @offer, status: :created, location: @offer }
      else
        format.html { render action: "new" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /offers/1
  # PUT /offers/1.json
  def update
    @offer = Offer.find(params[:id])

    respond_to do |format|
      if @offer.update_attributes(params[:offer])
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy

    respond_to do |format|
      format.html { redirect_to offers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.haml
= form_for @offer do |f|
  -if @offer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@offer.errors.count, "error")} prohibited this offer from being saved:"
      %ul
        - @offer.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label "Perfil Profesional"
    = select_tag :profile_ids, options_from_collection_for_select(Profile.find(:all), :id, :name), {include_blank: true, multiple: true}
  .field
    = f.label "Qué debe saber?"
    = text_area_tag :skills
  .field
    = f.label "Qué va a aprender?"
    = text_area_tag :wanted_skills
  .field
    = f.label "Ciudad"
    = select :city ,:city_id, @cities, include_blank: "-"
  .field
    = f.label "Titulo de la Oferta (Opcional)"
    = f.text_field :name
  .field
    = f.label "Descripción (Opcional)"
    = f.text_area :description, rows: 3
  
  .actions
    = f.submit 'Guardar', :class => "btn btn-primary"

app/views/offers/edit.html.haml
%h1 Editing offer

= render 'form'

= link_to 'Show', @offer
\|
= link_to 'Back', offers_path

app/views/offers/index.html.haml
%h1 Listing offers

%table
  %tr
    %th Enterprise
    %th Name
    %th Description
    %th City
    %th
    %th
    %th

  - @offers.each do |offer|
    %tr
      %td= offer.enterprise.try(:name)
      %td= offer.name
      %td= offer.description
      %td= offer.city_id
      %td= link_to 'Show', offer
      %td= link_to 'Edit', edit_offer_path(offer)
      %td= link_to 'Destroy', offer, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Offer', new_offer_path

app/views/offers/new.html.haml
- content_for :javascript do  
  = javascript_include_tag "/chosen/chosen.jquery.min"
  = stylesheet_link_tag "/chosen/chosen"

%h1 Nueva Oferta
= render 'form'
= link_to 'Back', offers_path

app/views/offers/show.html.haml
%p#notice= notice

%p
  %b Enterprise:
  = @offer.enterprise_id
%p
  %b Name:
  = @offer.name
%p
  %b Description:
  = @offer.description
%p
  %b City:
  = @offer.city_id

= link_to 'Edit', edit_offer_path(@offer)
\|
= link_to 'Back', offers_path